services:
  clienttrack_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clienttrack_backend
    env_file:
      - .env
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/app
    depends_on:
      clienttrack_db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  clienttrack_db:
    image: postgres:16
    container_name: clienttrack_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    container_name: clienttrack_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: clienttrack_prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10m"
    ports:
      - "9091:9090"
    depends_on:
      - clienttrack_backend

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: clienttrack_postgres_exporter
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_EXPORTER_DSN}
    ports:
      - "9187:9187"
    depends_on:
      - clienttrack_db

  grafana:
    image: grafana/grafana:latest
    container_name: clienttrack_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: clienttrack_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: clienttrack_kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  pgdata:
  redis_data:
  grafana_data:
  prometheus_data:
  esdata:
