"""tasks add reminder_sent

Revision ID: 2d6a80f35c00
Revises: f7a34338441b
Create Date: 2025-12-09 19:27:54.129011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d6a80f35c00"
down_revision: Union[str, Sequence[str], None] = "f7a34338441b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("reminder_sent", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "reminder_sent")
    # ### end Alembic commands ###
