"""increase otp_code length

Revision ID: 73bc77c65eeb
Revises: af9f1e7118d0
Create Date: 2025-11-29 14:22:50.593855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73bc77c65eeb"
down_revision: Union[str, Sequence[str], None] = "af9f1e7118d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "otp_code",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "otp_code",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
