"""cascade delete emails

Revision ID: 7456af8d9672
Revises: c97b48c46d07
Create Date: 2025-12-13 14:03:06.895414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7456af8d9672"
down_revision: Union[str, Sequence[str], None] = "c97b48c46d07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("emails_client_id_fkey", "emails", type_="foreignkey")
    op.create_foreign_key(
        None, "emails", "clients", ["client_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "emails", type_="foreignkey")
    op.create_foreign_key(
        "emails_client_id_fkey",
        "emails",
        "clients",
        ["client_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
