"""clients add company logo

Revision ID: 7943975b5e79
Revises: 2d6a80f35c00
Create Date: 2025-12-10 18:27:53.845579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7943975b5e79"
down_revision: Union[str, Sequence[str], None] = "2d6a80f35c00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("company_logo", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "company_logo")
    # ### end Alembic commands ###
