"""“clients_add_attachments”

Revision ID: 9d56489bfef6
Revises: d935f08d3504
Create Date: 2025-12-06 11:23:18.269099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d56489bfef6"
down_revision: Union[str, Sequence[str], None] = "d935f08d3504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("attachments", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "attachments")
    # ### end Alembic commands ###
