"""fix attachments to jsonb

Revision ID: a813737d9861
Revises: 9d56489bfef6
Create Date: 2025-12-06 14:03:49.290847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a813737d9861"
down_revision: Union[str, Sequence[str], None] = "9d56489bfef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients", "attachments", type_=sa.JSON(), postgresql_using="attachments::jsonb"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients", "attachments", type_=sa.TEXT(), postgresql_using="attachments::text"
    )
    # ### end Alembic commands ###
