"""add_email_verification

Revision ID: aaf48cae1c61
Revises: ce3a049c35e4
Create Date: 2025-11-28 16:23:57.667559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aaf48cae1c61"
down_revision: Union[str, Sequence[str], None] = "ce3a049c35e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients", "surname", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "phone", existing_type=sa.VARCHAR(length=40), nullable=True
    )
    op.alter_column(
        "clients", "company", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("clients", "notes", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "clients", "source", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "status", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "category", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "industry", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "latitude", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "clients", "longitude", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("otp_code", sa.String(length=6), nullable=True))
    op.add_column(
        "users", sa.Column("otp_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "users", "surname", existing_type=sa.VARCHAR(length=150), nullable=True
    )
    op.drop_index("ix_users_name", table_name="users")
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.drop_index("ix_users_surname", table_name="users")
    op.create_index(op.f("ix_users_surname"), "users", ["surname"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_surname"), table_name="users")
    op.create_index("ix_users_surname", "users", ["surname"], unique=True)
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.create_index("ix_users_name", "users", ["name"], unique=True)
    op.alter_column(
        "users", "surname", existing_type=sa.VARCHAR(length=150), nullable=False
    )
    op.drop_column("users", "otp_expires_at")
    op.drop_column("users", "otp_code")
    op.drop_column("users", "is_verified")
    op.alter_column(
        "clients", "longitude", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "clients", "latitude", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "clients", "industry", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "clients", "category", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "clients", "status", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "clients", "source", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("clients", "notes", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "clients", "company", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "clients", "phone", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    op.alter_column(
        "clients", "surname", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
