"""“users_add_pending_new_email”

Revision ID: ccf3599c28d2
Revises: 5ccf01cd0ce0
Create Date: 2025-12-02 15:57:46.610112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccf3599c28d2"
down_revision: Union[str, Sequence[str], None] = "5ccf01cd0ce0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("pending_new_email", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_new_email")
    # ### end Alembic commands ###
