"""“users_add_avatar_path”

Revision ID: d935f08d3504
Revises: ccf3599c28d2
Create Date: 2025-12-05 20:27:14.829165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d935f08d3504"
down_revision: Union[str, Sequence[str], None] = "ccf3599c28d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar_path", sa.String(length=500), nullable=True)
    )
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###
