"""update tasks timestamps to timezone aware

Revision ID: f7a34338441b
Revises: dd30742662e7
Create Date: 2025-12-07 19:44:52.137327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7a34338441b"
down_revision: Union[str, Sequence[str], None] = "dd30742662e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "tasks", "status", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "tasks",
        "due_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column("tasks", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("tasks", "client_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.drop_index("ix_tasks_id", table_name="tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_tasks_id", "tasks", ["id"], unique=False)
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column("tasks", "client_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("tasks", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "tasks",
        "due_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks", "status", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "tasks", "title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
